codecov:
  require_ci_to_pass: true
coverage:
  precision: 2
  range:
    - 60.0
    - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 80.0
    project:
      default:
        target: 80.0
github_checks:
  annotations: true

ignore:
  - build
  - example
  - app
  - tools
