from_json – forsus
from_json Subroutine
MPL
27 statements
Source File
public impure elemental subroutine from_json(self, name, json_str, path)
Uses
json_module
From a json file and a model name set the present groups.
Type Bound
Groups
Arguments
Type Intent Optional Attributes Name
class(Groups), intent(inout) :: self
Groups
character(len=*), intent(in) :: name
Model name
character(len=*), intent(in) :: json_str
json file
character(len=*), intent(in), optional :: path
Path to file
Calls
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: base
integer, public :: count
logical, public :: found
integer, public :: i
integer, public :: id
character(len=50), public :: idx
type(json_file), public :: json
character(len=:), public, allocatable :: str
Call graph
from_json calls get, open_json
open_json calls failed, initialize, load_file