from_json – forsus
from_json Subroutine
MPL
9 statements
Source File
public impure elemental subroutine from_json(self, json_str, path)
Read all the critical properties from a json file.
Type Bound
CriticalConstants
Arguments
Type Intent Optional Attributes Name
class(CriticalConstants), intent(inout) :: self
character(len=*), intent(in) :: json_str
character(len=*), intent(in), optional :: path
Calls
Called by
Call graph
from_json calls scalar_from_json
scalar_from_json calls get, initialize, load_file, open_json
open_json calls initialize, load_file, failed
init_json calls from_json
substance calls init_json