init_json – forsus
init_json Function
MPL
32 statements
Source File
public function init_json(name, path, only)
Initialize a Substance object from a json file, provided it’s name. It is also optional to use a custom path for the component.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Component’s name
character(len=*), intent(in), optional :: path
Optional database path
character(len=*), intent(in), optional :: only(:)
Only extract this parameters, the options are:
“critical”: Tc, Pc and Acentric Factor
“unifac_vle”: UNIFAC-VLE (Original UNIFAC) parameters
“parachor”: Parachor
“mathiascopeman”: Mathias Copeman function parameters
Return Value type(Substance)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: file
integer, public :: i
Call graph
init_json calls from_json
from_json calls scalar_from_json
scalar_from_json calls get, initialize, load_file, open_json
open_json calls initialize, load_file, failed
substance calls init_json