open_json – forsus
open_json Function
MPL
22 statements
Source File
public function open_json(json_str, path) result(json)
Uses
json_module
iso_fortran_env
forsus_constants
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: json_str
character(len=*), intent(in), optional :: path
Return Value type(json_file)
Calls
Called by
Call graph
open_json calls failed, initialize, load_file
from_json calls open_json, scalar_from_json
scalar_from_json calls open_json
init_json calls from_json
substance calls init_json