scalar_from_json – forsus
scalar_from_json Subroutine
MPL
22 statements
Source File
public impure elemental subroutine scalar_from_json(self, name, json_str, path)
Uses
iso_fortran_env
Setup a scalar property from a provided json key and json file path.
Type Bound
ScalarProperty
Arguments
Type Intent Optional Attributes Name
class(ScalarProperty), intent(inout) :: self
character(len=*), intent(in) :: name
Property name. Should be the key in the json file.
character(len=*), intent(in) :: json_str
json file relative path to executable.
character(len=*), intent(in), optional :: path
json file relative path to executable.
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(json_file), public :: json
Call graph
scalar_from_json calls get, initialize, load_file, open_json
open_json calls initialize, load_file, failed
from_json calls scalar_from_json
init_json calls from_json
substance calls init_json